# Generated by Django 5.1.6 on 2025-04-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Income",
            fields=[],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Income",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.payment",),
        ),
        migrations.AddField(
            model_name="payment",
            name="type",
            field=models.CharField(
                choices=[("IN", "Income"), ("EX", "Expense")], max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="sales.sale",
            ),
        ),
    ]
