# Generated by Django 5.1.6 on 2025-04-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_income_payment_type_alter_payment_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[],
            options={
                "verbose_name": "Expense",
                "verbose_name_plural": "Expenses",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("payments.payment",),
        ),
    ]
