# Generated by Django 5.1.6 on 2025-05-03 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="date",
            field=models.DateField(),
        ),
    ]
