# Generated by Django 5.1.6 on 2025-04-07 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockIn",
            fields=[],
            options={
                "verbose_name": "Stock In",
                "verbose_name_plural": "Stock In Records",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.stocktransaction",),
        ),
        migrations.CreateModel(
            name="StockOut",
            fields=[],
            options={
                "verbose_name": "Stock Out",
                "verbose_name_plural": "Stock Out Records",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("stock.stocktransaction",),
        ),
    ]
