# Generated by Django 5.1.6 on 2025-04-07 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0006_alter_part_break_even_price_alter_part_selling_price"),
        ("stock", "0002_stockin_stockout"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stocktransaction",
            name="part",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_transactions",
                to="parts.part",
            ),
        ),
    ]
