# Generated by Django 5.1.6 on 2025-04-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0003_alter_stocktransaction_part"),
    ]

    operations = [
        migrations.AddField(
            model_name="stocktransaction",
            name="amount",
            field=models.DecimalField(decimal_places=0, default=3000, max_digits=10),
            preserve_default=False,
        ),
    ]
