# Generated by Django 5.1.6 on 2025-04-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock", "0004_stocktransaction_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stocktransaction",
            name="amount",
        ),
    ]
