# Generated by Django 5.1.6 on 2025-04-02 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PartCategory",
            new_name="PartType",
        ),
        migrations.RemoveField(
            model_name="part",
            name="category",
        ),
        migrations.RemoveField(
            model_name="part",
            name="price",
        ),
        migrations.AddField(
            model_name="part",
            name="_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parts",
                to="parts.parttype",
            ),
        ),
        migrations.AddField(
            model_name="part",
            name="break_even_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="part",
            name="part_number",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="part",
            name="selling_price",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
