# Generated by Django 5.1.6 on 2025-04-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0002_rename_partcategory_parttype_remove_part_category_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="part",
            old_name="_type",
            new_name="type",
        ),
    ]
