# Generated by Django 5.1.6 on 2025-04-03 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0003_rename__type_part_type"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PartType",
            new_name="PartCategory",
        ),
    ]
