# Generated by Django 5.1.6 on 2025-04-03 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0004_rename_parttype_partcategory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partcategory",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
