# Generated by Django 5.1.6 on 2025-04-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parts", "0005_alter_partcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="break_even_price",
            field=models.DecimalField(decimal_places=0, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name="part",
            name="selling_price",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=20, null=True
            ),
        ),
    ]
