# Generated by Django 5.1.6 on 2025-04-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("stock", "0005_remove_stocktransaction_amount"),
    ]

    operations = [
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "type",
                    models.CharField(
                        choices=[("other", "Other"), ("stock", "Stock")], max_length=20
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                ("date", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "re_stocks",
                    models.ManyToManyField(
                        blank=True, null=True, to="stock.stocktransaction"
                    ),
                ),
            ],
        ),
    ]
