# Generated by Django 5.1.6 on 2025-04-25 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
        ("stock", "0005_remove_stocktransaction_amount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sale",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="sale",
            name="total_amount",
        ),
        migrations.AddField(
            model_name="sale",
            name="comments",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="stock_out",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stock.stockout",
            ),
        ),
        migrations.AlterField(
            model_name="saleitem",
            name="unit_price",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
