# Generated by Django 5.1.6 on 2025-04-25 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_remove_sale_customer_remove_sale_total_amount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="quantity",
        ),
    ]
