# Generated by Django 5.1.6 on 2025-05-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0003_remove_saleitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="date",
            field=models.DateField(),
        ),
    ]
