# Generated by Django 5.1.6 on 2025-05-03 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0004_alter_sale_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="unit_price",
        ),
    ]
