# Generated by Django 5.1.6 on 2025-05-09 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0005_remove_saleitem_unit_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="saleitem",
            name="part",
        ),
    ]
